name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  standard:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.4']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run standard
      run: bundle exec standardrb --format github

  reek:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.4']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run reek
      run: bundle exec reek

  rspec:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3.3', '3.2.4']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Specs
      run: bundle exec rspec
